/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValueChainRouteImport } from './routes/value-chain'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SpeciesRouteImport } from './routes/species'
import { Route as RndRouteImport } from './routes/rnd'
import { Route as ProcessingCenterRouteImport } from './routes/processing-center'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MakersIndexRouteImport } from './routes/makers.index'
import { Route as SpeciesIdRouteImport } from './routes/species.$id'
import { Route as MakersIdRouteImport } from './routes/makers.$id'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'

const ValueChainRoute = ValueChainRouteImport.update({
  id: '/value-chain',
  path: '/value-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesRoute = SpeciesRouteImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => rootRouteImport,
} as any)
const RndRoute = RndRouteImport.update({
  id: '/rnd',
  path: '/rnd',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingCenterRoute = ProcessingCenterRouteImport.update({
  id: '/processing-center',
  path: '/processing-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MakersIndexRoute = MakersIndexRouteImport.update({
  id: '/makers/',
  path: '/makers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesIdRoute = SpeciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpeciesRoute,
} as any)
const MakersIdRoute = MakersIdRouteImport.update({
  id: '/makers/$id',
  path: '/makers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/modules': typeof ModulesRoute
  '/processing-center': typeof ProcessingCenterRoute
  '/rnd': typeof RndRoute
  '/species': typeof SpeciesRouteWithChildren
  '/terms': typeof TermsRoute
  '/value-chain': typeof ValueChainRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/makers/$id': typeof MakersIdRoute
  '/species/$id': typeof SpeciesIdRoute
  '/makers/': typeof MakersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/modules': typeof ModulesRoute
  '/processing-center': typeof ProcessingCenterRoute
  '/rnd': typeof RndRoute
  '/species': typeof SpeciesRouteWithChildren
  '/terms': typeof TermsRoute
  '/value-chain': typeof ValueChainRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/makers/$id': typeof MakersIdRoute
  '/species/$id': typeof SpeciesIdRoute
  '/makers': typeof MakersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/modules': typeof ModulesRoute
  '/processing-center': typeof ProcessingCenterRoute
  '/rnd': typeof RndRoute
  '/species': typeof SpeciesRouteWithChildren
  '/terms': typeof TermsRoute
  '/value-chain': typeof ValueChainRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/makers/$id': typeof MakersIdRoute
  '/species/$id': typeof SpeciesIdRoute
  '/makers/': typeof MakersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/contact'
    | '/gallery'
    | '/modules'
    | '/processing-center'
    | '/rnd'
    | '/species'
    | '/terms'
    | '/value-chain'
    | '/articles/$slug'
    | '/makers/$id'
    | '/species/$id'
    | '/makers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/contact'
    | '/gallery'
    | '/modules'
    | '/processing-center'
    | '/rnd'
    | '/species'
    | '/terms'
    | '/value-chain'
    | '/articles/$slug'
    | '/makers/$id'
    | '/species/$id'
    | '/makers'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/contact'
    | '/gallery'
    | '/modules'
    | '/processing-center'
    | '/rnd'
    | '/species'
    | '/terms'
    | '/value-chain'
    | '/articles/$slug'
    | '/makers/$id'
    | '/species/$id'
    | '/makers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ModulesRoute: typeof ModulesRoute
  ProcessingCenterRoute: typeof ProcessingCenterRoute
  RndRoute: typeof RndRoute
  SpeciesRoute: typeof SpeciesRouteWithChildren
  TermsRoute: typeof TermsRoute
  ValueChainRoute: typeof ValueChainRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  MakersIdRoute: typeof MakersIdRoute
  MakersIndexRoute: typeof MakersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/value-chain': {
      id: '/value-chain'
      path: '/value-chain'
      fullPath: '/value-chain'
      preLoaderRoute: typeof ValueChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species': {
      id: '/species'
      path: '/species'
      fullPath: '/species'
      preLoaderRoute: typeof SpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rnd': {
      id: '/rnd'
      path: '/rnd'
      fullPath: '/rnd'
      preLoaderRoute: typeof RndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing-center': {
      id: '/processing-center'
      path: '/processing-center'
      fullPath: '/processing-center'
      preLoaderRoute: typeof ProcessingCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makers/': {
      id: '/makers/'
      path: '/makers'
      fullPath: '/makers/'
      preLoaderRoute: typeof MakersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/$id': {
      id: '/species/$id'
      path: '/$id'
      fullPath: '/species/$id'
      preLoaderRoute: typeof SpeciesIdRouteImport
      parentRoute: typeof SpeciesRoute
    }
    '/makers/$id': {
      id: '/makers/$id'
      path: '/makers/$id'
      fullPath: '/makers/$id'
      preLoaderRoute: typeof MakersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SpeciesRouteChildren {
  SpeciesIdRoute: typeof SpeciesIdRoute
}

const SpeciesRouteChildren: SpeciesRouteChildren = {
  SpeciesIdRoute: SpeciesIdRoute,
}

const SpeciesRouteWithChildren =
  SpeciesRoute._addFileChildren(SpeciesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ModulesRoute: ModulesRoute,
  ProcessingCenterRoute: ProcessingCenterRoute,
  RndRoute: RndRoute,
  SpeciesRoute: SpeciesRouteWithChildren,
  TermsRoute: TermsRoute,
  ValueChainRoute: ValueChainRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  MakersIdRoute: MakersIdRoute,
  MakersIndexRoute: MakersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
